version: '3.8'

services:
  consul:
    image: consul:1.11.0
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    volumes:
      - ./consul-data:/consul/data

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - consul
    environment:
      DB: consul
      DBPORT: "8500"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  consul-data:
  prometheus-data:
  grafana-data:
